---
abstract: 'object oriented parser for fixed width records'
author:
  - osfameron
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-FixedRecord
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  DateTime::Format::Strptime: 0
  List::Util: 0
  Moose: 0
  MooseX::ClassAttribute: 0
  MooseX::Types: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
