---
abstract: 'object oriented parser for fixed width records'
author:
  - 'and LICENSE'
  - osfameron
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-FixedRecord
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  DateTime::Format::Duration: 0
  DateTime::Format::Strptime: 0
  List::Util: 0
  Moose: 1.15
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
